%pouya 6/26/18
%plots and saves spatial figures based on daily variables generated by M03_wrfout_Explorer_mac_v15_combinedDomains_daily:
% data_in_daily
% date_time_daily
% varunit: unit
% vardesc: description
% data_LU_INDEX: land cover data
% data_XLAT: land cover data
% data_XLONG: land cover data

clear 
close all
clc

% addpath('/Volumes/GoogleDrive/My Drive/5.Projects/7.WRF-UCM_WaterDemand_ClimateChange/2.WRF_PostProcessing/0.Pouya_matlab_fx')
addpath('/Volumes/GoogleDrive/My Drive/5.Projects/6.LBNL_Bay_Area_Climate_Readiness_Project_part3/2.WRF_PostProcessing/0.Pouya_matlab_fx')
addpath('/Volumes/GoogleDrive/My Drive/PROJECTS/2016_Ultra_High_Res_Climate_Modeling_LDRD_and_MLA/STUDY 2018 Climate Change Extreme Heat Exposure CA/2.WRF_PostProcessing/0.Pouya_matlab_fx')
%%
% folder that processed data is saved
runname1='S31_base_ens01_WRFRun_';plot_runname1='BASE'        ;pop_scenario1='Y2010A2';
runname2='S31_cnrm_ens01_WRFRun_';plot_runname2='CNRM'        ;pop_scenario2='Y2010A2';
runname3='S41_cnrm_ens01_WRFRun_';plot_runname3='CNRMcoolRoof';pop_scenario3='Y2010A2';
runname4='S31_hadg_ens01_WRFRun_';plot_runname4='HADG'        ;pop_scenario4='Y2010A2';
runname5='S41_hadg_ens01_WRFRun_';plot_runname5='HADGcoolRoof';pop_scenario5='Y2010A2';

foldername='/Volumes/PVahmani_G_RAID/Projects/6.LBNL_Bay_Area_Climate_Readiness_Project_part3/2.WRF_Outputs_daily_daytime';
Savefolder='/Volumes/GoogleDrive/My Drive/5.Projects/7.WRF-UCM_WaterDemand_ClimateChange/2.WRF_PostProcessing/2.Figures/1.Spatial';
Savefolder='/Volumes/GoogleDrive/My Drive/PROJECTS/2019_IM3_Phase_1/STUDY 2020 ET-Irrigation and Climate Change/2.WRF_PostProcessing/2.Figures/1.Spatial';
if ~exist(Savefolder,'dir')
    mkdir(Savefolder)
end

% Variables
Variables_dirOutputs0={'LU_INDEX' 'VEGFRA' 'FRC_URB2D' 'UTYPE_URB' 'LAI' 'HGT' 'ALBEDO' 'ZNT'}';%'XLAT' 'XLONG' 'TH2' 'ISLTYP' 'EMISS' 'SHDMAX' 'SHDMIN' 'IVGTYP'
Variables_dirOutputs1={'T2' 'TSK' 'NOAHRES' 'RAINNC' 'PBLH' 'SST' 'ACGRDFLX' 'ACHFX' 'ACLHF' 'ACLWDNB' 'ACLWUPB' 'ACSWDNB' 'ACSWUPB'}';%'SFROFF' 'UDROFF'
Variables_dirOutputs2={'HFX' 'LH' 'GRDFLX' 'QFX' 'PSFC' 'V10' 'U10' 'Q2'}';% 'CLDFRA' 'SMOIS' 'TSLB' 'SWDOWN' 'GLW' 'TC_URB' 
Variables_calculated1={'SMOIS1' 'SMOIS2' 'SMOIS3' 'RA' 'GSVPT' 'ACNETRAB' 'ACNETRAB_star' 'ACNETRAB_star2' 'RH' 'WIND' 'ET' 'ET2' 'VPD'}';%'RHatT2max' 'RHatT2min' 'TV' 'DTR' 'CDD' 'HE35' 'HElo' 'T2MAX' 'T2MIN' 'Irrigation' 'SMOIS4' 'CLDFRA01' 'CLDFRA02' 'CLDFRA25'
Variables=[Variables_calculated1;Variables_dirOutputs1;Variables_dirOutputs0;Variables_dirOutputs2];clear Variables_*
%land only variables: water = NaN
Variables_landOnly={'SMOIS1' 'SMOIS2' 'SMOIS3' 'SMOIS4' 'TC_URB' 'TSLB' 'SMOIS' 'SFROFF' 'UDROFF' 'IVGTYP' 'ISLTYP' 'VEGFRA' 'GRDFLX' 'FRC_URB2D' 'UTYPE_URB' 'LAI' 'NOAHRES' 'Irrigation'}';
%water only variables
Variables_waterOnly={'SST'}';
%accumulated variables
Variables_Accumulated={'ACNETRAB_star' 'ACNETRAB_star2' 'ET' 'ET2' 'QFX' 'CDD' 'HE35' 'HElo' 'Irrigation'  'RAINNC' 'SFROFF' 'UDROFF' 'NOAHRES' 'ACGRDFLX' 'ACHFX' 'ACLHF' 'ACLWDNB' 'ACLWUPB' 'ACSWDNB' 'ACSWUPB' 'ACNETRAB'};
%zero or one variables: such as extreme heat days: for these variable if
%the average over a county is about 0.5 it would be 1 for that county
Variables_0or1={};%{'HE35'};

% Include populatin?
popOption=0;
pop_filename='/Volumes/GoogleDrive/My Drive/5.Projects/7.WRF-UCM_WaterDemand_ClimateChange/5.Population';
pop_filename='/Volumes/GoogleDrive/My Drive/PROJECTS/2019_IM3_Phase_1/STUDY 2020 ET-Irrigation and Climate Change/5.Population';

%land cover land use of interest
hiUrb=24;meUrb=25;loUrb=26;
agric=38;
water=17;
land=100;land_nonurb=101;land_nonag=102;land_nonurb_nonag=103;
all=1000;
%set the land cover land use of interest for each domain
LULC ={agric;[hiUrb;meUrb;loUrb];land_nonurb_nonag;water};clear hiUrb meUrb loUrb agric water land land_nonurb land_nonag land_nonurb_nonag all
LULCc={'g';'r';'k';'b'};
LULCl={'agric';'urb';'land_nonurb_nonag';'water'};
%% load basics
%data_XLAT,data_XLONG,data_LU_INDEX
[ ~,~,~,~,data_XLAT,data_XLONG,data_LU_INDEX ] = pouya_Processedwrfout_matlab_read_daily_daytime( foldername,runname1,'ET2'           );
DATA_LU_INDEX=zeros(size(data_LU_INDEX,1),size(data_LU_INDEX,2),15);
for k=1:15
    DATA_LU_INDEX(:,:,k)=data_LU_INDEX;
end;clear k
DATA_LU_INDEX=single(DATA_LU_INDEX);
%only CA and ocean 
ca_poly_on_in_withOcean = pouya_CA_only_tight_withOcean( data_XLONG,data_XLAT );
CA_poly_on_in_withOcean=zeros(size(ca_poly_on_in_withOcean,1),size(ca_poly_on_in_withOcean,2),15);
for k=1:15
    CA_poly_on_in_withOcean(:,:,k)=ca_poly_on_in_withOcean;
end;clear k ca_poly_on_in_withOcean
CA_poly_on_in_withOcean=single(CA_poly_on_in_withOcean);
%%
for var_i=[13]%9,10,14,15,17,19,33,35,36,37,42%[4,5]%[4,5,8,9,13]%length(Variables)%[13,10,14,7,17,18,19]%:4%

varname=Variables{var_i};

% baseline
[ data1_in_daily,date_time_daily,varunit,vardesc,data_XLAT,data_XLONG,data_LU_INDEX ] = pouya_Processedwrfout_matlab_read_daily_daytime( foldername,runname1,varname );
data1_in=squeeze(mean(data1_in_daily,3));clear data1_in_daily
data1_in(~CA_poly_on_in_withOcean)=NaN;
  
for run=[4,2]%[4,2,5,3]
    eval(sprintf('runname_2=runname%d',run))
    eval(sprintf('plot_runname=plot_runname%d',run))
    filename=sprintf('Spatial_%s-baseline_v4',plot_runname);
    savefolder=sprintf('%s/%s',Savefolder,filename);
    if ~exist(savefolder,'dir')
        mkdir(savefolder)
    end

%scenario
[ data2_in_daily,       ~       ,   ~   ,   ~   ,   ~     ,    ~     ,      ~       ] = pouya_Processedwrfout_matlab_read_daily_daytime( foldername,runname_2,varname );
data2_in=squeeze(mean(data2_in_daily,3));clear data2_in_daily
data2_in(~CA_poly_on_in_withOcean)=NaN;

base=data1_in;
est =data2_in;

% statistics
stat_base= pouya_time_series2( base, data_LU_INDEX, LULC, LULCl );
stat_est = pouya_time_series2( est , data_LU_INDEX, LULC, LULCl );

%calc changes
delta=(est-base);
% statistics
stat_delta= pouya_time_series2( delta, data_LU_INDEX, LULC, LULCl );

% plot spatial options
urban_border=1;
county_border=0;
state_border=1;

% plot spatial base
plot_data=nanmean(base,3);
if ~strcmp(varname,'SST');plot_data(data_LU_INDEX==17)=NaN;end
cmin_diff=prctile(plot_data(:),1 );
cmax_diff=prctile(plot_data(:),99);
cpt=NaN;%'YlOrRd_09';
pouya_fig_geoshow_with_cptcmapOption_agBorder(cpt,plot_data,data_XLAT,data_XLONG,data_LU_INDEX,cmin_diff,cmax_diff,urban_border,county_border,state_border);
title(sprintf('%s (%s) \n%f(%s),%f(%s),%f(%s),%f(%s)',varname,varunit,nanmean(stat_base.agric),LULCl{1,1},nanmean(stat_base.urb),LULCl{2,1},nanmean(stat_base.land_nonurb_nonag),LULCl{3,1},nanmean(stat_base.water),LULCl{4,1}),'FontSize',9);
savename=sprintf('%s/%s_Base_Spatial',savefolder,varname);
saveas(gca,strcat(savename,'.fig'));
set(gcf,'Units','pixels');scrpos = get(gcf,'Position');newpos = scrpos/100;set(gcf,'PaperUnits','inches','PaperPosition',newpos);%Make the output file the same size as the figure on the screen
print('-dpng', strcat(savename,'.png'), '-r300');

% plot spatial changes red blue
plot_data=nanmean(delta,3);
if ~strcmp(varname,'SST');plot_data(data_LU_INDEX==17)=NaN;end
plot_data(plot_data==0)=NaN;%make zeros white
cmin_diff=-1*max(abs(prctile(plot_data(:),0.1)),abs(prctile(plot_data(:),99.9)));
cmax_diff=   max(abs(prctile(plot_data(:),0.1)),abs(prctile(plot_data(:),99.9)));
cpt='Oranges_09_strong_Blues_09';
pouya_fig_geoshow_with_cptcmapOption_agBorder(cpt,plot_data,data_XLAT,data_XLONG,data_LU_INDEX,cmin_diff,cmax_diff,urban_border,county_border,state_border);
title(sprintf('%s (%s) change\n%f(%s),%f(%s),%f(%s),%f(%s)',varname,varunit,nanmean(stat_delta.agric),LULCl{1,1},nanmean(stat_delta.urb),LULCl{2,1},nanmean(stat_delta.land_nonurb_nonag),LULCl{3,1},nanmean(stat_delta.water),LULCl{4,1}),'FontSize',9);
savename=sprintf('%s/%s_Change_Spatial',savefolder,varname);
saveas(gca,strcat(savename,'.fig'));
set(gcf,'Units','pixels');scrpos = get(gcf,'Position');newpos = scrpos/100;set(gcf,'PaperUnits','inches','PaperPosition',newpos);%Make the output file the same size as the figure on the screen
print('-dpng', strcat(savename,'.png'), '-r300');

%calc percent changes
delta_perc=(est-base)./base*100;
%avoid unrealistic percentage changes over close to zero baselines (this mostly affect error bars)
delta_perc(base<=prctile(base(:),0.1))=NaN;
fprintf('note: %s < %f (%s) were not condidered in perc change calc\n',varname,prctile(base(:),0.1),varunit);

% statistics
stat_delta_perc= pouya_time_series2( delta_perc,data_LU_INDEX, LULC, LULCl );

% plot spatial percent change
plot_data=nanmean(delta_perc,3);
if ~strcmp(varname,'SST');plot_data(data_LU_INDEX==17)=NaN;end
plot_data(plot_data==0)=NaN;%make zeros white
cmin_diff=-30;
cmax_diff= 30;
cpt='Oranges_09_strong_Blues_09';
pouya_fig_geoshow_with_cptcmapOption_agBorder(cpt,plot_data,data_XLAT,data_XLONG,data_LU_INDEX,cmin_diff,cmax_diff,urban_border,county_border,state_border);
title(sprintf('%s percent change\n%2.0f(%s),%2.0f(%s),%2.0f(%s),%2.0f(%s)',varname,nanmean(stat_delta_perc.agric),LULCl{1,1},nanmean(stat_delta_perc.urb),LULCl{2,1},nanmean(stat_delta_perc.land_nonurb_nonag),LULCl{3,1},nanmean(stat_delta_perc.water),LULCl{4,1}),'FontSize',9);
savename=sprintf('%s/%s_PercChange_Spatial',savefolder,varname);
saveas(gca,strcat(savename,'.fig'));
set(gcf,'Units','pixels');scrpos = get(gcf,'Position');newpos = scrpos/100;set(gcf,'PaperUnits','inches','PaperPosition',newpos);%Make the output file the same size as the figure on the screen
print('-dpng', strcat(savename,'.png'), '-r300');

% plot bar percent change
plot_data    =[nanmean(stat_delta_perc.agric) nanmean(stat_delta_perc.urb) nanmean(stat_delta_perc.land_nonurb_nonag)]; 
plot_data_err=[nanstd( stat_delta_perc.agric) nanstd( stat_delta_perc.urb) nanstd( stat_delta_perc.land_nonurb_nonag)]; 
figure('position',[1000,1000,250,500]);
bar(1:3,plot_data,'FaceColor',[0.9290,0.6940,0.1250])   
hold on
er = errorbar(1:3,plot_data,plot_data_err,plot_data_err);    
er.Color = [0 0 0];                            
er.LineStyle = 'none'; 
ylim([-20 20]);
set(gca,'YTick',(-20:10:20));
set(gca,'YTickLabel',{'-20%','-10%','0','10%','20%'});
set(gca,'YAxisLocation','right');
set(gca,'XTickLabel',{'ag.','urb.','land'});
set(gca,'FontSize',18);
hold off
title(sprintf('%s percent change\n%2.0f(%s),%2.0f(%s),%2.0f(%s),%2.0f(%s)',varname,nanmean(stat_delta_perc.agric),LULCl{1,1},nanmean(stat_delta_perc.urb),LULCl{2,1},nanmean(stat_delta_perc.land_nonurb_nonag),LULCl{3,1},nanmean(stat_delta_perc.water),LULCl{4,1}),'FontSize',9);
savename=sprintf('%s/%s_PercChange_Bar',savefolder,varname);
saveas(gca,strcat(savename,'.fig'));
title('');
set(gca,'XTickLabel',{''});
set(gcf,'Units','pixels');scrpos = get(gcf,'Position');newpos = scrpos/100;set(gcf,'PaperUnits','inches','PaperPosition',newpos);%Make the output file the same size as the figure on the screen
print('-dpng', strcat(savename,'.png'), '-r300');

%save data
savename=sprintf('%s/%s_StatData.mat',savefolder,varname);
save(savename,'varname','varunit','stat_base','stat_est','stat_delta','stat_delta_perc','-v7.3')


end %runname_2

end %var_i
